name: tests
on: [pull_request, push]
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: ['22.x', '24.x', '26.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test
